<script setup lang="ts">
import {ref,watch} from 'vue'
import {usePanelAccount,errorText} from '../composables/usePanelAccount'
import {panelRequest,accountPath,type Dialog,type Page,type Group} from '../lib/api/communications'
import {useConfirm} from '../composables/useConfirm'
const {store,account,error}=usePanelAccount();const {confirm}=useConfirm();const groups=ref<Dialog[]>([]),detail=ref<Group|null>(null),busy=ref(false),more=ref(false),success=ref('');let gen=0,detailGen=0,offset=0
async function load(append=false){if(!account.value)return;const n=++gen;try{const p=await panelRequest<Page<Dialog>>(`${accountPath(account.value)}/groups?offset=${append?offset:0}&limit=50`);if(n!==gen)return;groups.value=append?[...groups.value,...p.items]:p.items;more.value=p.has_more;offset=p.next_offset??0}catch(e){if(n===gen)error.value=errorText(e)}}
watch(account,()=>{detail.value=null;groups.value=[];detailGen++;void load()})
async function select(id:string){const n=++detailGen;detail.value=null;error.value='';success.value='';try{const d=await panelRequest<Group>(`${accountPath(account.value)}/groups/${encodeURIComponent(id)}`);if(n===detailGen)detail.value=d}catch(e){if(n===detailGen)error.value=errorText(e)}}
async function save(){if(!detail.value)return;busy.value=true;error.value='';try{await panelRequest(`${accountPath(account.value)}/groups/${encodeURIComponent(detail.value.id)}`,'PUT',{title:detail.value.title,description:detail.value.description});success.value='群资料已更新';await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
async function leave(){if(!detail.value||!await confirm({title:'退出群聊',message:`确认退出「${detail.value.title}」？重新加入可能需要邀请。`,danger:true}))return;try{await panelRequest(`${accountPath(account.value)}/groups/${encodeURIComponent(detail.value.id)}/leave`,'POST');detail.value=null;await load()}catch(e){error.value=errorText(e)}}
</script>
<template><div class="panel-stack"><section class="panel-card"><h2 class="panel-title">群聊管理</h2><p class="panel-muted">查看已加入的群聊、编辑群资料或打开会话。修改资料需要相应管理员权限。</p><select v-model="account" class="panel-input mt-5" aria-label="操作账号"><option value="" disabled>选择账号</option><option v-for="a in store.accounts" :key="a.name">{{a.name}}</option></select></section><p v-if="error" class="panel-error">{{error}}</p><p v-if="success" class="panel-success">{{success}}</p><div class="panel-columns"><section class="panel-card panel-stack"><h3>已加入的群聊</h3><p v-if="!groups.length" class="panel-empty">暂无群聊</p><button v-for="g in groups" :key="g.id" class="panel-button justify-between" @click="select(g.id)"><span>{{g.title}}</span><span class="panel-muted text-xs">{{g.id}}</span></button><button v-if="more" class="panel-button" @click="load(true)">加载更多</button></section><form v-if="detail" class="panel-card panel-stack" @submit.prevent="save"><div class="panel-row"><h3>群资料</h3><RouterLink class="panel-button" :to="{name:'chats',query:{account}}">打开聊天中心</RouterLink></div><p class="panel-muted">{{detail.members_count??'—'}} 位成员 · {{detail.id}}</p><label>群名称<input v-model="detail.title" class="panel-input mt-2" required maxlength="128"/></label><label>群简介<textarea v-model="detail.description" class="panel-input mt-2" rows="5" maxlength="255"/></label><div class="panel-row"><button type="button" class="panel-button danger" :disabled="busy" @click="leave">退出群聊</button><button class="panel-button primary" :disabled="busy">保存资料</button></div></form></div></div></template>
