<script setup lang="ts">
import {ref,watch} from 'vue'
import {Send,Workflow} from 'lucide-vue-next'
import {usePanelAccount,errorText} from '../composables/usePanelAccount'
import {listDialogs,sendMessage,type Dialog} from '../lib/api/communications'
import {createSignTask} from '../lib/api/sign-tasks'
import {getAuthToken} from '../lib/api/core'
import {useConfirm} from '../composables/useConfirm'
const {store,account,error}=usePanelAccount();const {confirm}=useConfirm();const selected=ref<string[]>([]),dialogs=ref<Dialog[]>([]),targets=ref<string[]>([]),text=ref(''),mode=ref('now'),time=ref('09:00'),name=ref(''),busy=ref(false),result=ref('');let generation=0
watch(account,a=>{if(a&&!selected.value.length)selected.value=[a]})
watch(selected,async accounts=>{const gen=++generation;targets.value=[];dialogs.value=[];error.value='';if(!accounts.length)return;try{const pages=await Promise.all(accounts.map(async a=>{let items:Dialog[]=[];let offset=0;for(let i=0;i<200;i++){const p=await listDialogs(a,'',offset,false,'groups');items.push(...p.items);if(!p.has_more)break;offset=p.next_offset??offset+50}return items}));if(gen!==generation)return;dialogs.value=(pages[0]??[]).filter(d=>pages.every(p=>p.some(x=>x.id===d.id)))}catch(e){if(gen===generation)error.value=errorText(e)}})
async function submit(){if(busy.value||!selected.value.length||!targets.value.length||!text.value.trim())return;if(mode.value==='schedule'&&targets.value.some(id=>!Number.isSafeInteger(Number(id)))){error.value='群聊 ID 超过浏览器安全整数范围，请在任务编排中创建此任务';return}if(!await confirm({title:mode.value==='now'?'发送群消息':'创建定时任务',message:`将对 ${selected.value.length} 个账号的 ${targets.value.length} 个群聊${mode.value==='now'?'立即发送消息':'创建每日发送任务'}，是否继续？`}))return;busy.value=true;error.value='';result.value='';let sent=0;try{if(mode.value==='now'){for(const a of selected.value)for(const chat of targets.value){await sendMessage(a,chat,text.value);sent++}result.value=`已成功发送 ${sent} 条消息`}else{await createSignTask(getAuthToken(),{name:name.value.trim(),account_name:selected.value[0]!,account_names:selected.value,sign_at:time.value,execution_mode:'fixed',chats:targets.value.map(id=>({chat_id:Number(id),name:dialogs.value.find(d=>d.id===id)?.title||id,action_interval:1,actions:[{action:1,text:text.value}]}))});result.value='定时任务已创建，可在任务编排中查看与停用'}}catch(e){error.value=(sent?`已有 ${sent} 条发送成功，剩余未执行。`:'')+errorText(e)}finally{busy.value=false}}
</script>
<template><div class="panel-stack"><section class="panel-card"><p class="panel-eyebrow"><Workflow :size="18"/>多账号操作与会话策略</p><h2 class="panel-title">账号工作台</h2><p class="panel-muted">选择一个或多个账号，向共同加入的群聊发送消息。定时发送会创建独立任务并保留运行记录。</p></section><p v-if="error" class="panel-error" role="alert">{{error}}</p><p v-if="result" class="panel-success" role="status">{{result}}</p><section class="panel-card panel-stack"><h3>选择账号与共有群</h3><div class="panel-columns"><label>操作账号（可多选）<select v-model="selected" class="panel-input mt-3" multiple size="4" :disabled="busy"><option v-for="a in store.accounts" :key="a.name" :value="a.name">{{a.name}}</option></select></label><label>目标会话（可多选）<select v-model="targets" class="panel-input mt-3" multiple size="4" :disabled="busy"><option v-for="d in dialogs" :key="d.id" :value="d.id">{{d.title}}</option></select></label></div><p class="panel-muted text-sm">仅显示所有选中账号都加入的群聊。电脑可按 Ctrl / Command 多选。</p></section><form class="panel-card panel-stack" @submit.prevent="submit"><h3 class="flex items-center gap-3"><Send :size="20"/>群消息操作</h3><div class="panel-columns"><label>发送方式<select v-model="mode" class="panel-input mt-3" :disabled="busy"><option value="now">立即发送</option><option value="schedule">每日定时发送</option></select></label><label v-if="mode==='schedule'">执行时间（服务器时区）<input v-model="time" type="time" required class="panel-input mt-3"/></label></div><label v-if="mode==='schedule'">任务名称<input v-model="name" required maxlength="80" class="panel-input mt-3"/></label><label>消息内容<textarea v-model="text" rows="7" class="panel-input mt-3" required :disabled="busy" placeholder="输入要发送到所选群聊的消息"/></label><div class="panel-row"><p class="panel-muted">目标：{{selected.length}} 个账号 × {{targets.length}} 个共有群</p><button class="panel-button primary" :disabled="busy||!targets.length||!selected.length">{{busy?'正在处理…':mode==='now'?'立即发送':'创建定时任务'}}</button></div></form></div></template>
